# Generated by Django 4.2.7 on 2024-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=150)),
                ("contact", models.CharField(max_length=25)),
            ],
        ),
    ]
